### ISSUE TITLE
Splitting frames that are not leaves of the binary tree 

### ISSUE THREAD

**Issue by elvisjauld** [herbstluftwm/herbstluftwm#906]
Hello!
I'm not sure if this is the right place to ask, but I've read the man and I cannot figure out a way to easily change the layout of frames so that a non-leaf frame is split.
Basically I would like to change the layout in the following way:
```                     
 A | B     ->       _A_|_B_
                       C
```
by splitting the root frame (or any other frame that is not a leaf).
Is there a way to reorganize the tree like this in herbstluftwm without relying on scripts ?

I've been following this project for a little while. I really like herbstluftwm, but never got to stick with it. The recent and exciting developments,  as well as all the friendly and open discussions I see in the issue section, have encouraged me to switch from bspwm. Thank you for this!

**Comment by t-wissmann** [comment]
Hi,

> Basically I would like to change the layout in the following way:
> 
> ```
>  A | B     ->       _A_|_B_
>                        C
> ```

So you'd like to what the following shell script does?

```
herbstclient load "(split vertical:0.5:1 $(herbstclient dump) (clients horizontal:0))"
```

You're right, that this is not possible directly in hlwm. The main reason for this is that I didn't come up with a good way of specifying a user interface this split. One can think of having a command like: `split_at_root horizontal|vertical` but I have no idea how to specify a clean/easy interface for splitting frames somewhere within the tree.

The only way I can think of it at the moment is to add another parameter to the `split` command that contains the frame index of the frame that should be split (and the defualt argument is `@`, refering to the focused frame(-leaf)).

What do you think?


> I've been following this project for a little while. I really like herbstluftwm, but never got to stick with it. The recent and exciting developments, as well as all the friendly and open discussions I see in the issue section, have encouraged me to switch from bspwm. Thank you for this!

Thanks and welcome on board!

**Comment by bew** [comment]
Maybe it would help to be able to focus a non-leaf frame?
The UI would then be pretty straight forward, maybe with a different focus color so we can differentiate leaf vs non-leaf frames.

> add another parameter to the `split` command that contains the frame index of the frame that should be split (with default to `@`)

This looks good too IMO!

**Comment by elvisjauld** [comment]
Hi, thanks for the response !
> So you'd like to what the following shell script does?

Yes, I wrote  a little script to split the root frame in a given direction, but was wondering if there was a native way to do this. 

> The only way I can think of it at the moment is to add another parameter to the split command that contains the frame index of the frame that should be split (and the defualt argument is @, refering to the focused frame(-leaf)).

I had exactly this in mind, it would be very interesting to be able to specify the path of the frame, with an argument like `split frame_index="01e" left 0.5`.
In my opinion, it would even be perfect if we had on top of that a way to select the parent of the current frame (for instance with a "p" character that could be passed in the frame_index). 

> Maybe it would help to be able to focus a non-leaf frame?

This would definitely be a nice way to solve this!

**Comment by blarz** [comment]
This should be fixed with #980 being merged

**Comment by bew** [comment]
> Maybe it would help to be able to focus a non-leaf frame?

Should I open a separate issue for this? I think it would definitely help to do the splitting interactively

**Comment by t-wissmann** [comment]
> > Maybe it would help to be able to focus a non-leaf frame?
> 
> Should I open a separate issue for this? I think it would definitely help to do the splitting interactively

No, because I will not implement this, because it makes too much of a mess (conceptually and compared to the current implementation)

**Comment by bew** [comment]
> > > Maybe it would help to be able to focus a non-leaf frame?
> > 
> > 
> > Should I open a separate issue for this? I think it would definitely help to do the splitting interactively
> 
> No, because I will not implement this, because it makes too much of a mess (conceptually and compared to the current implementation)

Thanks for your answer, I understand how it can become messy..

---

About another suggestion from @blarz:
> add a way to select the parent of the current frame (for instance with a "p" character that could be passed in the frame_index).

And another from me I just thought about (quoting it to "highlight" it):

> Add the `parent`, `index` and `parent_index` attributes to frame objects so we can programmatically get index of the N'th 

I think these 2 would better fit into the existing design of herbstluftwm, what do you think?

**Comment by t-wissmann** [comment]
> About another suggestion from @blarz:
> 
> > add a way to select the parent of the current frame (for instance with a "p" character that could be passed in the frame_index).
> 
> And another from me I just thought about (quoting it to "highlight" it):
> 
> > Add the `parent` (returning a frame object), `index` and `parent_index` attributes to frame objects so we can programmatically get index of the N'th
> 
> I think these 2 would better fit into the existing design of herbstluftwm, what do you think?

Definitely, yes! I've added the "p" frame index as PR #984 and the `index` attribute as PR #985. The `parent` is still missing, because here I need to be careful not to create cycles in the frame tree. This is however only an implementational thing where one needs to be careful (and nothing conceptually like the 'focusing non-leaf frames')
